FROM node:16
RUN apt-get update && apt-get install libvips-dev -y
ENV NOOE_ENV=development
WORKDIR /opt/
COPY ./package.json ./package-lock.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm install --platform=linux --arch=x64 sharp
RUN npm install --ignore-scripts=false --foreground-scripts --verbose sharp
COPY ./ .
WORKDIR /opt/app/
EXPOSE 1337
CMD [ "npm", "run", "develop" ]